tasks:
  - name: dev server
    init: pdm sync
    command: pdm serve
  
image:
  file: .gitpod.Dockerfile

ports:
  - name: website
    port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - yzhang.markdown-all-in-one
