site_name: Unturned 3 Knowledgebase
site_url: https://unturned.info
repo_name: unturned-3-knowledgebase
repo_url: https://github.com/unturned-info/unturned-3-knowledgebase
site_description: >-
  Documentation for various features of Unturned 3.0
  Including modding, server hosting, and more.
theme:
  name: material
  custom_dir: overrides
  logo: img/Unturned_Logo.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  analytics:
    provider: google
    property: G-KXF0XQF85N
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/PgJCPh6
      name: unturned.info Discord
    - icon: material/keyboard-space
    - icon: fontawesome/brands/steam
      link: https://store.steampowered.com/app/304930/Unturned/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/unturned 
      name: Unturned Official Discord
    - icon: fontawesome/brands/discourse
      link: https://forum.smartlydressedgames.com
      name: SDG Forums
    - icon: fontawesome/brands/wordpress  
      link: https://blog.smartlydressedgames.com
      name: SDG Blog
  unity:
    version: '2019.4'
    download-link: 
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      provider: 'github'
      repo: 'unturned-3-knowledgebase'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
plugins:
  - git-revision-date-localized:
      type: date
  - search
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'Server Hosting/ServerHosting.md': 'Server-Hosting/ServerHosting.md'
        'Server Hosting/PortForwarding.md': 'Server-Hosting/PortForwarding.md'
        'Server Hosting/Rocket.md': 'Server-Hosting/Rocket.md'
        'Server Hosting/GameServerLoginTokens.md': 'Server-Hosting/GameServerLoginTokens.md'
        'Server Hosting/Extending Servers/CommandIO.md': 'Server-Hosting/Extending-Servers/CommandIO.md'
        'Server Hosting/Extending Servers/CraftingBlacklistAsset.md': 'Server-Hosting/Extending-Servers/CraftingBlacklistAsset.md'
        'Server Hosting/Extending Servers/DedicatedWorkshopUpdateMonitor.md': 'Server-Hosting/Extending-Servers/DedicatedWorkshopUpdateMonitor.md'
        'Modding/Asset Properties References/ItemData.md': 'Modding/AssetPropertiesReferences/ItemData.md'
        'Modding/Asset Properties References/VehicleData.md': 'Modding/AssetPropertiesReferences/VehicleData.md'
        'Modding/Asset Types/AssetsV1.md': 'Modding/AssetTypes/AssetsV1.md'
        'Modding/Asset Types/AssetsV2.md': 'Modding/AssetTypes/AssetsV2.md'
        'support/Common Issues.md': 'support/CommonIssues.md'


  # Site page tree
nav:
  # Do not use '\', it will explode the build system
  - Overview: 'index.md'
  - Modding:
    - 'Modding/GettingStarted.md'
    - 'Modding/Layers.md'
    - 'Modding/AssetBundles.md'
    - 'Modding/GUID.md'
    - 'Modding/ModHooks.md'
    - Assets:
      - 'Modding/AssetTypes/AssetsV1.md'
      - 'Modding/AssetTypes/AssetsV2.md'
      - 'Modding/AssetPtr.md'
      - 'Modding/MasterBundlePtr.md'
    - 'Modding/AirdropAsset.md'
    - 'Modding/Animation.md'
    - 'Modding/AssetValidation.md'
    - 'Modding/CharacterMeshReplacement.md'
    - 'Modding/Currency.md'
    - 'Modding/StereoSongAsset.md'
    - 'Modding/Unity2018.md'
    - 'Modding/WeatherAsset.md'
    - Asset Properties References:
      - 'Modding/AssetPropertiesReferences/ItemData.md'
      - 'Modding/AssetPropertiesReferences/VehicleData.md'
      - 'Modding/VehiclePhysicsProfile.md'
    - Mapmaking:
      - 'Modding/mapmaking/FavqqoriteSearches.md'
      - 'Modding/mapmaking/CuratedMaps.md'
      - 'Modding/mapmaking/Foliage.md'
      - 'Modding/mapmaking/Landscape.md'
      - 'Modding/mapmaking/LevelAsset.md'
      - 'Modding/mapmaking/LevelConfig.md'
  - Server Hosting:
    - Getting Started:
      - 'Server-Hosting/Getting-Started/ServerHosting.md'
      - 'Server-Hosting/Getting-Started/PortForwarding.md'
    - Server Configuration:
      - 'Server-Hosting/Server-Configuration/Commands.dat.md'
      - 'Server-Hosting/Server-Configuration/Config.json.md'
      - 'Server-Hosting/Server-Configuration/WorkshopDownloadConfig.json.md'
    - Modules & Plugins:
      - 'Server-Hosting/Modules-Plugins/Rocket.md'
    - Extending Servers:
      - 'Server-Hosting/Extending-Servers/CommandIO.md'
      - 'Server-Hosting/Extending-Servers/CraftingBlacklistAsset.md'
      - 'Server-Hosting/Extending-Servers/DedicatedWorkshopUpdateMonitor.md'
    - Explanations:
      - 'Server-Hosting/Explanations/CuratedMaps.md'
      - 'Server-Hosting/Explanations/Monetization.md'
      - 'Server-Hosting/Explanations/GameServerLoginTokens.md'
      - 'Server-Hosting/Explanations/GameUpdateNotifications.md'
  - Support:
    - 'support/Troubleshooting/LogFiles.md'
    - 'support/Troubleshooting/verifyGameFiles.md'
    - 'support/Troubleshooting/workshopFolder.md'
