name: Deploy MKDocs
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # This is needed for article revision dates, it fetches all git history 
              fetch-depth: 0
      - uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.8  # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64    # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          enable-pep582: true  # Enable PEP 582 package loading globally
      - name: Install dependencies
        run: pdm sync
      - name: Build MKdocs
        run: pdm deploy
